services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_GOOGLE_CLIENT_ID=13221455025-6o0vld5bhb71o1ji5uesjajfbfcqjgj4.apps.googleusercontent.com
      - VITE_FACEBOOK_APP_ID=898735686475077
      - VITE_BACKEND_API=http://localhost:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:p@ssw0rd@host.docker.internal:3306/contract
      - JWT_SECRET=jssdjaosdjasdsakdkasdmasdgyqwerqrfsf
